repos:

- repo: local

  hooks:

  - id: mh_version
    name: mh_version
    entry: mh_style
    args: [-v]
    verbose: true
    language: python
    additional_dependencies: [miss_hit_core]

  - id: mh_style
    name: mh_style
    entry: mh_style
    args: [--process-slx, --fix]
    files: ^(.*\.(m|slx))$
    language: python
    additional_dependencies: [miss_hit_core]

  - id: mh_metric
    name: mh_metric
    entry: mh_metric
    args: [--ci]
    files: ^(.*\.(m|slx))$
    language: python
    additional_dependencies: [miss_hit_core]

  - id: mh_lint
    name: mh_lint
    entry: mh_lint
    files: ^(.*\.(m|slx))$
    language: python
    additional_dependencies: [miss_hit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
